name: Ethers Test

on:
  workflow_dispatch:   # allows manual trigger
  push:
    branches: [ main ]

jobs:
  run-ethers:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install deps
        run: npm install

      # 4️⃣ Run the ethers.js script
      - name: Run ethers.js script
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: node scripts/test.js

